add-not-within done
MatanYadaev/laravel-eloquent-spatial pull request #54
Opened 2022-09-20 10:46 UTC by dzhwar-k

I've added a negate of the **whereWithin** function, it seems necessary.

Regards.

2022-09-20 14:19 UTC, MatanYadaev requested changes
Hi @dzhwar-k, thanks for the PR.

Please add tests for this new method, and document the method in the API.md file.

2022-09-20 14:19 UTC, MatanYadaev commented on src/SpatialBuilder.php
> +      ) . ' = 0 '
This will make it a bit more readable
```suggestion
      sprintf(
        'ST_WITHIN(%s, %s) = 0',
        "`{$column}`",
        $this->toExpression($geometryOrColumn),
      )
```

2022-09-20 14:20 UTC, MatanYadaev commented
BTW - it will be great if you could add also a `whereNotContains` method.

2022-09-21 12:36 UTC, dzhwar-k commented
Greetings.
I've made the changes

2022-09-21 16:25 UTC, MatanYadaev requested changes
Just last few changes.

2022-09-21 16:25 UTC, MatanYadaev commented on .vscode/settings.json
> +}
Can you please remove this file?

2022-09-21 16:25 UTC, MatanYadaev commented on .vscode/settings.json
> +}
If you wish, you can add `.vscode` to the `.gitignore`

2022-09-21 16:25 UTC, MatanYadaev commented on tests/SpatialBuilderTest.php
> +  $anotherPointOutsidePolygon = new Point(55, 55, 4326);
Unnecessary point IMO. There's already one point inside and one point outside. How it enriches the test?

2022-09-21 16:25 UTC, MatanYadaev commented on tests/SpatialBuilderTest.php
> +  expect($testPlacesNotWithinPolygon)->toHaveCount(2);
Please add this explicit assertion.
```suggestion
  expect($testPlacesNotWithinPolygon)->toHaveCount(1);
  expect($testPlacesNotWithinPolygon[0]->point)->toEqual($pointOutsidePolygon);
```

2022-09-22 06:11 UTC, dzhwar-k commented
I've removed unnecessary point and files.

2022-09-22 13:51 UTC, merged

2022-09-22 13:53 UTC, MatanYadaev commented
@dzhwar-k Thanks! :)