Add a manual casting method, fixes #69
MatanYadaev/laravel-eloquent-spatial pull request #70
Opened 2022-12-07 17:37 UTC by Synchro

Here's a PR adding a method (with a test!) that generates an `Expression` that can be used for manual casting along the lines of what I was asking in #69. I'm not sure about the name, or whether you think this is incomplete!

2022-12-11 10:22 UTC, MatanYadaev requested changes
Thanks for the PR. I left a few comments.

2022-12-11 10:22 UTC, MatanYadaev commented on src/GeometryCast.php
> +  public static function forDB(ConnectionInterface $connection, Geometry $geometry): Expression
1. Move this method to be under `Geometry`
2. Name it `toSqlExpression`
3. Instead of using `$geometry` use just `$this`
4. I think you can remove the doc block because it will be straight-forward
5. Document it in the `API.md` file
6. Move the test to `GeometryTest` as well

2022-12-11 10:22 UTC, MatanYadaev commented on tests/GeometryCastTest.php
> +it('creates a database-ready value string from a geometry', function (): void {
```suggestion
it('creates an SQL expression from a geometry', function (): void {
```

2022-12-11 10:22 UTC, MatanYadaev commented on tests/GeometryCastTest.php
> +});
Please duplicate this test. One test for DBs that support axis order, and one for DBs that don't support.
You can see an example here: https://github.com/MatanYadaev/laravel-eloquent-spatial/blob/master/tests/Objects/GeometryTest.php#L41

2022-12-11 10:22 UTC, MatanYadaev commented on src/GeometryCast.php
>      return DB::raw("ST_GeomFromText('{$wkt}', {$value->srid}, 'axis-order=long-lat')");
Please use `$geometry->toSqlExpression($connection)` here. Do the same at `SpatialBuilder@toExpression`

2022-12-12 16:12 UTC, MatanYadaev requested changes

2022-12-12 16:12 UTC, MatanYadaev commented on .run/Test.run.xml
> +    </CommandLine>
Local environment variable - should be removed.
```suggestion
```

2022-12-12 16:12 UTC, MatanYadaev commented on API.md
> +* `toSqlExpression()` - Returns an Eloquent Expression of the field, for use in manually constructed SQl statements.
```suggestion
* `toSqlExpression(ConnectionInterface $connection)` - Serializes the geometry object into an SQL query.
```

2022-12-12 16:12 UTC, MatanYadaev commented on tests/Objects/GeometryTest.php
> +    ->toEqual('ST_GeomFromText(\'POINT(180 0)\', 4326, \'axis-order=long-lat\')');
```suggestion
    ->toEqual("ST_GeomFromText('POINT(180 0)', 4326, 'axis-order=long-lat')");
```

2022-12-12 16:12 UTC, MatanYadaev commented on tests/Objects/GeometryTest.php
> +    ->toEqual('ST_GeomFromText(\'POINT(180 0)\', 4326)');
```suggestion
    ->toEqual("ST_GeomFromText('POINT(180 0)', 4326)");
```

2022-12-12 16:12 UTC, MatanYadaev commented on src/Objects/Geometry.php
> +  public function toSqlExpression(ConnectionInterface $connection): Expression
Please use this method in `GeometryCast@set` and at SpatialBuilder@toExpression. Currently, the exact same logic is duplicated in these 3 places.

2022-12-12 16:31 UTC, Synchro commented
I've done all those (and it's much cleaner) - but I don't see why this merge conflict is happening when it's a straight addition

2022-12-12 17:34 UTC, MatanYadaev approved these changes

2022-12-12 17:35 UTC, MatanYadaev commented
@Synchro I updated the `GeometryTest` on `master`, please rebase and fix the conflicts. It's should be simple.

2022-12-12 19:21 UTC, merged

2022-12-12 19:23 UTC, MatanYadaev commented
@Synchro Fixed the conflicts. Thanks!