Unserialize array-to-model with geometry
MatanYadaev/laravel-eloquent-spatial pull request #71
Opened 2022-12-07 23:09 UTC by trin4ik

At now we can do `$serialize = Model::find(35)->toArray();` but cant use `$model = new Model($serialize)`. This PR look to values and try to use `Geometry::fromJson()` to serialized array.

2022-12-11 10:32 UTC, MatanYadaev requested changes
Thanks for the PR. Please add tests. This package should be 100% covered with tests.

2022-12-11 10:32 UTC, MatanYadaev commented on src/GeometryCast.php
> +        $value = Geometry::fromJson(json_encode($value));
Please add a `Geometry@fromArray` method that does the same logic and use it here instead.

2022-12-12 06:49 UTC, trin4ik commented
hi, tests added, method `fromArray` created

2022-12-12 11:40 UTC, MatanYadaev requested changes
Please use 2 spaces instead of 4.

2022-12-12 11:40 UTC, MatanYadaev commented on src/Objects/Geometry.php
> +        }
I believe this validation isn't necessary, we already validate for correctness of GeoJson here: https://github.com/MatanYadaev/laravel-eloquent-spatial/blob/master/src/Factory.php#L34

2022-12-12 11:40 UTC, MatanYadaev commented on src/Objects/Geometry.php
> +    public static function fromArray(array $geometry): static
Please add this method to the `API.md`

2022-12-12 11:40 UTC, MatanYadaev commented on tests/Objects/GeometryCollectionTest.php
> +    $geometryCollectionFromArray = GeometryCollection::fromArray($geometryCollection->toArray());
I tend to keep the tests following the [AAA pattern](https://github.com/goldbergyoni/javascript-testing-best-practices#-%EF%B8%8F-12-structure-tests-by-the-aaa-pattern) - so anything that is related to arranging the data should be above the "act" part.
```suggestion
    $geometryCollection = new GeometryCollection([
      new Polygon([
        new LineString([
          new Point(0, 180),
          new Point(1, 179),
          new Point(2, 178),
          new Point(3, 177),
          new Point(0, 180),
        ]),
      ]),
      new Point(0, 180),
    ]);
    $geometryCollectionArray = $geometryCollection->toArray();

    $geometryCollectionFromArray = GeometryCollection::fromArray($geometryCollectionArray);
```

2022-12-12 11:40 UTC, MatanYadaev commented on tests/Objects/GeometryCollectionTest.php
> +it('creates geometry collection from array (serialized model)', function (): void {
Please move the test to the `GeometryTest` because it's not related to a specific geometry type.

2022-12-12 12:51 UTC, trin4ik commented
- codestyle fixed
- throw `OutOfBoundsException` removed
- API documented
- test moved and fixed.

also added some test. How u run a tests? i use https://github.com/nektos/act and when i run pest/pest-coverage, i see a lot of coverage errors

![image](https://user-images.githubusercontent.com/839633/207049402-5e491bfe-03be-4869-b39e-9e2ab41a01bf.png)

2022-12-12 15:41 UTC, merged

2022-12-12 15:41 UTC, MatanYadaev commented
@trin4ik Thanks!