Reusable trait rather than adding a method
MatanYadaev/laravel-eloquent-spatial pull request #75
Opened 2023-01-04 15:55 UTC by lukevi

Hi - I made this small change locally to be more "the laravel way" and thought I'd share.

2023-01-05 08:49 UTC, MatanYadaev requested changes
Thanks for the PR! I left small comments.

2023-01-05 08:49 UTC, MatanYadaev commented on README.md
> +    use HasSpatial;
Please update line 59 to: 
```
Fill the `$fillable` and `$casts` arrays and use the `HasSpatial` trait in your new model:
```

2023-01-05 08:49 UTC, MatanYadaev commented on src/Traits/HasSpatial.php
> +}
Please add a newline at the end of the file.

2023-01-05 08:49 UTC, MatanYadaev commented on tests/TestModels/TestPlace.php
> - * @method static SpatialBuilder<TestPlace> query()
You shouldn't remove this phpDoc property. You can read about it here: https://github.com/MatanYadaev/laravel-eloquent-spatial#tip-for-better-ide-support

2023-01-05 17:40 UTC, lukevi commented
Very welcome - it's my first ever open-source contribution, so I'm glad you like it. Updates pushed.

2023-01-07 10:51 UTC, MatanYadaev requested changes
You have lint issues, please run `composer run php-cs-fixer` to fix these issues.

2023-01-07 10:51 UTC, MatanYadaev commented on README.md
> +Fill the `$fillable` and `$casts` arrays and use the `hastSpatial` trait in your new model:
Typo :)
```suggestion
Fill the `$fillable` and `$casts` arrays and use the `HasSpatial` trait in your new model:
```

2023-01-07 10:51 UTC, MatanYadaev commented on tests/TestModels/TestPlace.php
> +use MatanYadaev\EloquentSpatial\Traits\HasSpatial;
You need to import `SpatialBuilder` because it is used in line 29.
```suggestion
use MatanYadaev\EloquentSpatial\SpatialBuilder;
use MatanYadaev\EloquentSpatial\Traits\HasSpatial;
```

2023-01-09 14:23 UTC, lukevi commented on README.md
> +Fill the `$fillable` and `$casts` arrays and use the `hastSpatial` trait in your new model:
well that's embarrassing - better now.

2023-01-09 14:45 UTC, MatanYadaev approved these changes

2023-01-09 14:46 UTC, merged

2023-01-09 14:46 UTC, MatanYadaev commented
Thanks!