Add Expression typehint to support passing DB::raw
MatanYadaev/laravel-eloquent-spatial pull request #76
Opened 2023-01-25 01:01 UTC by Riley19280

Currently, the column parameters on the SpatialBuilder class are typehinted as string, so when passing a `DB::raw(...)` expression into the builder, it gets casted to a string first, then re-wrapped as a column value. This causes issues when attempting a query like
 `->whereWithin(DB::raw('point(longitude, latitude)'), MultiPolygon::fromWkt(...))`, 
resulting in `point(longitude, latitude)` being treated as a column name in sql. By avoiding the string cast, the actual raw value passed is used. 

The fix for this was to add the `Expression` typehint (what `DB::raw` returns) so that the implicit string cast does not happen. This is then picked up by the `$this->getQuery()->getGrammar()->wrap` calls (see [here](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Grammar.php#L55-L57), and then [here](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Grammar.php#L216-L219)) resulting in a correct raw value in the sql.

2023-01-25 06:12 UTC, MatanYadaev commented
Hi @Riley19280 , thanks for the PR.

1. Can you add tests?
2. Please update the typehint in the API.md file
3. Do you think the second parameter should also accept expression?

2023-01-25 15:03 UTC, Riley19280 commented
Yeah, I can add tests. It does probably make sense for the second one to do so as well, and also run the first parameter through the `toExpression` function as well, so that it can also handle geometries.

2023-02-05 22:49 UTC, Riley19280 commented
@MatanYadaev I made the changes requested, including expanding support for `DB::raw` and `Geometry` for both parameters for all functions. The unit tests for the `toExpressionString` method should suffice for this support, but also added a real world test for my use case.

2023-02-06 09:12 UTC, MatanYadaev requested changes
Thanks!

Can you update the method signatures on API.md?

2023-02-06 13:23 UTC, Riley19280 commented on src/SpatialBuilder.php
> +    ExpressionContract|Geometry|string $column,
I cannot imagine all of the possible use cases for each method, but i figured that its best to be more flexible, rather than arbitrarily restrict what is allowed.

2023-02-06 13:42 UTC, Riley19280 commented
> Can you update the method signatures on API.md?

Updated, I left off the `ExpressionContract` as I feel it clutters the docs and is something that anyone could reasonably expect to be supported if they need to use it.

2023-02-06 19:25 UTC, MatanYadaev approved these changes

2023-02-06 19:26 UTC, merged

2023-02-06 20:39 UTC, MatanYadaev commented
Thanks for the contribution @Riley19280 🙏